version: '3'
services:
  # Appach
  app:
    container_name: damp_app
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./htdocs:/var/www/html
      - ./log/app:/var/log
    ports:
      - 8080:80

  # MySQL
  db:
    image: mariadb
    container_name: damp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_board
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # - ./mysql/data/mysql:/var/lib/mysql # for docker for windows/mac
      - db_vol:/var/lib/mariadb # for dockertoolbox
      - ./mysql/entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: damp_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    volumes:
      - ./log/pma:/var/log
    ports:
      - 1234:80
    depends_on:
      - db

# For dockertool box
volumes:
  db_vol:
